baseURL: "/"
languageCode: "en-us"
title: "Marlon Rodríguez Flor"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     - identifier: blog
#       name: Blog
#       title: Blog posts
#       url: /blogs
#       weight: 1
#     - identifier: gallery
#       name: Gallery
#       title: Blog posts
#       url: /gallery
#       weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Marlon Rodríguez Flor"
  description: This is Marlon's profile.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav_marlon.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Marlon Rodríguez Flor" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false
      disablePublications: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Marlon."
    subtitle: "Computer Science Engineer \nData Scientist"
    content: "Passionate about the development of artificial intelligence models for discovering the stories behind data."
    image: /images/hero.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/CV_Marlon2024_ESP.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/rmarlon308
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/marlon-rodriguez-flor/
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a data scientist pursuing a Master's degree in Data Science at the Autonomous University of Madrid, currently working on my Master's thesis with a focus on artificial intelligence. I hold an engineering degree in Computer Science from San Francisco de Quito University. Throughout my career, I have developed and implemented numerous machine learning models that drive business value. My professional experience includes working at Banco Solidario S.A., where I led data analytics projects and developed interactive dashboards to enhance customer experience and sales efficiency.

      I have expertise in various artificial intelligence techniques and statistical analysis, I have worked with machine learning and deep learning for Natural Language Processing (NLP), Computer Vision, Biometrics and recommendation systems. I have earned several certifications from MITx MicroMasters in data analysis, statistics, and machine learning. My research, published in IEEE, highlights my contributions to machine learning and path planning optimization. Additionally, I am fluent in both Spanish and English.

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "R"
        - "Java"
        - "SQL"
        - "Spark"
        - "C++"
        - "Dart"
        - "C#"
        - "CSS"
        - "HTML"
        - "LaTeX"

  # Experience
  experience:
    enable: true
    title: "Experience"
    items:
      - job: "Data Analytics Officer"
        company: "Banco Solidario S.A."
        companyUrl: "https://www.banco-solidario.com/"
        date: "Jan 2022 - Ago 2023"
        icon: /images/bs.png
        # featuredLink:
        #   enable: true
        #   name: "View the project"
        #   url: "https://example.com"
        content:  |
          - Developed and implemented a Machine Learning model (SVM) to identify potential customers for increasing their savings account balances. This initiative identified over 38,000 clients, with 7% successfully increasing their balances by more than USD 260 each, resulting in a cumulative increase of USD 200,000 in savings account balances.
          - Provided leadership and collaborated closely with product owners in defining and developing projects, and effectively communicated findings and results to non-technical audiences.
      - job: "Data Analytics Technician"
        company: "Banco Solidario S.A."
        companyUrl: "https://www.banco-solidario.com/"
        date: "Jul 2021 - Dic 2021"
        icon: /images/bs.png
        content: |
          - Developed and implemented a Machine Learning model (Random Forest) to identify potential customers likely to download Banco Solidario's mobile application, enhancing customer segmentation. This initiative reduced download costs by 22% and increased application downloads by 30%.
          - Created an interactive dashboard to monitor sales and service efficiency in Banco Solidario's commercial advisors. This tool enables proactive actions at each branch, enhancing customer experience and sales outcomes.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master in Data Science"
        school:
          name: "Universidad Autónoma de Madrid (UAM)"
          url: "https://www.uam.es/uam/inicio"
          icon: /images/UAM+solo.svg
        date: "2023 - Present"
        # GPA: "3.8 out of 5.0"
        content: |-
          I expect to gradutate in January 2025.

          Extracurricular Activities:
          - Delegate of the Master in Data Science.
        subjects:
          enable: true
          title: "Some relevant subjects taken:"
          items:
            - "Advanced Methods in Machine Learning."
            - "Natural Language Processing (NLP)."
            - "Deep Learning for Signal Processing Image and Video."
            - "Reinforcement Learning."
            - "Advanced Methods in Statistics."
          
      - title: "Computer Science Engineering"
        school:
          name: "Universidad San Francisco de Quito (USFQ)"
          url: "https://www.usfq.edu.ec/es"
          icon: /images/logo-usfq-cropped.svg
        date: "2017 - 2021"
        # GPA: "3.9 out of 5.0"
        content: |-
          I published a paper in the 2021 IEEE Fifth Ecuador Technical Chapters Meeting (ETCM).
          - [Path Planning Optimization in SDN Using Machine Learning Techniques](https://ieeexplore.ieee.org/document/9590749).

        subjects:
          enable: true
          title: "Some relevant subjects taken:"
          items:
          - "Artificial Intelligence."
          - "Data Mining."
          - "Probability and Statistics."
          - "Linear Algebra."
          - "Calculus (I, II and III)."
          - "Programming (I, II and III)."
          - "Data Structures and Algorithms."
          - "Databases."
          - "Systems Design."

   # Publications
  publications:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Path Planning Optimization in SDN Using Machine Learning Techniques"
        school:
          name: "2021 IEEE Fifth Ecuador Technical Chapters Meeting (ETCM)"
          url: "https://attend.ieee.org/etcm-2021/"
          icon: /images/ieee-logo.png
        date: "Oct 2021"
        # GPA: "3.8 out of 5.0"
        featuredLink:
          enable: true
          name: Available on IEEE Xplore
          url: "https://ieeexplore.ieee.org/document/9590749"
        content: |-

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

# projects
  projects:
    enable: true
    title: "Some Projects"
    items:
      

      - title: Gradient Boosting Implementation
        content: This project features an implementation of the Gradient Boosting algorithm, an ensemble method that combines multiple decision trees (stumps). It utilizes gradient descent optimization to minimize the loss function. The collective contributions of all weak models (stumps) result in a robust predictive model.
        image: /images/projects/gb.png
        featured:
          name: Available on GitHub
          link: https://github.com/rmarlon308/Gradient-Boosting-Implementation
        badges:
          - "Python"
          - "Scikit-learn"
          - "Machine Learning (ML)"
          # links:
          #   - icon: fab fa-github
          #     url: https://github.com/gurusabarish/converter

      - title: Analysis of Emotions in Classic Novels
        content: This project uses Natural Language Processing (NLP) to analyze emotions in literary texts from Project Gutenberg, aiming to identify and quantify emotions through advanced NLP methods like sentiment analysis and text information extraction.
        image: /images/projects/emotion.png
        featured:
          name: Available on GitHub
          link: https://github.com/rmarlon308/Emotion-Analysis
        badges:
          - "Python"
          - "WordNet"
          - "Beautiful Soup"
          - "Natural Language Processing (NLP)"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/HugoProfileV2

      - title: Q Learning and SARSA Implementation
        content: "This project demonstrates the implementation of two reinforcement learning algorithms: Q Learning and SARSA. These algorithms are evaluated across various grid world maps to analyze their performance and behavior."
        image: /images/projects/coding.png
        featured:
          name: Available on GitHub
          link: https://github.com/rmarlon308/QLearning-and-SARSA-Implementation
        badges:
          - "Python"
          - "Reinforcement Learning (RL)"
        # links:
          # - icon: fa fa-envelope
            # url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          # - icon: fab fa-github
          #   url: https://github.com/rmarlon308/QLearning-and-SARSA-Implementation


  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:rmarlon308@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/rmarlon308
      linkedin: https://www.linkedin.com/in/marlon-rodriguez-flor/
        # twitter: https://twitter.com
        # instagram: https://instagram.com
        # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "Marlon Rodríguez. All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
